version: '3'
services:

  cape:
    restart: always
    container_name: cape 
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: ["server","--https-listen-port","6441"]
    tmpfs:
    - /run
    - /var/run
    privileged: true
    hostname: cape
    environment:
    - K3S_TOKEN=148021782618917
    - K3S_KUBECONFIG_OUTPUT=/cape/cape.yaml
    - K3S_KUBECONFIG_MODE=666
    - K3S_HTTPS_LISTEN_PORT=6441
    volumes:
    - ./kubeconfigs:/cape
    ports:
    - 6441:6441
    - 80:80

  cluster1:
    container_name: cluster1
    restart: always
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: ["server","--https-listen-port","1443"]
    tmpfs:
    - /run
    - /var/run
    privileged: true
    hostname: cluster1
    environment:
    - K3S_TOKEN=148021782618917
    - K3S_KUBECONFIG_OUTPUT=/cluster1/cluster1.yaml
    - K3S_KUBECONFIG_MODE=666
    - K3S_HTTPS_LISTEN_PORT=1441
    volumes:
    - ./kubeconfigs:/cluster1
    - ./manifests:/var/lib/rancher/k3s/server/manifests
    ports:
    - 1443:1443
    - 180:80

  cluster2:
    restart: always
    container_name: cluster2
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: ["server","--https-listen-port","2443"]
    tmpfs:
    - /run
    - /var/run
    privileged: true
    hostname: cluster2
    environment:
    - K3S_TOKEN=148021782618917
    - K3S_KUBECONFIG_OUTPUT=/cluster2/cluster2.yaml
    - K3S_KUBECONFIG_MODE=666
    - K3S_HTTPS_LISTEN_PORT=2443
    volumes:
    - ./kubeconfigs:/cluster2
    - ./manifests:/var/lib/rancher/k3s/server/manifests
    ports:
    - 2443:2443
    - 280:80
volumes:
  cape: {}
  cluster1: {}
  cluster2: {}
