version: '3'
services:

  server:
    container_name: server
    image: "rancher/k3s:v1.20.2-k3s1"
    restart: always
    tmpfs:
    - /run
    - /var/run
    command: server
    privileged: true
    hostname: server
    environment:
    - K3S_TOKEN=148021782618917
    - K3S_KUBECONFIG_OUTPUT=/kubeconfigs/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - ./kubeconfigs:/kubeconfigs
    ports:
    - 443:443
    - 6443:6443

  agent1:
    container_name: agent1
    image: "rancher/k3s:v1.20.2-k3s1"
    restart: always
    tmpfs:
    - /run
    - /var/run
    privileged: true
    hostname: agent1
    environment:
    - K3S_TOKEN=148021782618917
    - K3S_URL=https://server:6443
    ports:
    - 1443:443

  agent2:
    container_name: agent2
    image: "rancher/k3s:v1.20.2-k3s1"
    restart: always
    tmpfs:
    - /run
    - /var/run
    privileged: true
    hostname: agent2
    environment:
    - K3S_TOKEN=148021782618917
    - K3S_URL=https://server:6443
    ports:
    - 2443:443

volumes:
  server: {}
